apiVersion: v1
kind: Namespace
metadata:
  name: ${tenant_name}-app2
  labels:
    gwcp.guidewire.com/created-by: jdobson
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: jdobson
    gwcp.guidewire.com/tenant-name: ${tenant_name}
    gwcp.guidewire.com/version: experimental
